version: '3.8'

services:
  postgres:
    container_name: graphql-crud-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: graphql-crud-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d graphql-crud-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-crud-app:
    container_name: graphql-crud-app
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - /Users/pablosilva/Desktop/coding/studies/graphql-prisma-nest-crud:/usr/src/app
    ports:
      - 3333:3333
    command: /bin/sh -c "npx prisma generate && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:admin@graphql-crud-db:5432/graphql-crud-db?schema=public
